/** One nostalgic line per year. Shown right after someone picks their year. */
export const YEAR_FACTS: Record<number, string> = {
  1970: "Nace Unix. Todo lo que usas hoy tiene algo de ese año.",
  1971: "Se envía el primer correo electrónico. Nadie sabía que iba a llenar bandejas.",
  1972: "Dennis Ritchie crea C. Medio mundo todavía lo usa.",
  1973: "Se hace la primera llamada desde un celular. Pesaba un kilo.",
  1974: "Sale el Altair 8800 y empieza la era de la computadora personal.",
  1975: "Se funda Microsoft con un intérprete de BASIC.",
  1976: "Apple nace en un garaje. El Apple I costaba 666 dólares.",
  1977: "Sale el Apple II y la Atari 2600. Los videojuegos llegan a la sala.",
  1978: "Se envía el primer spam. Algunas cosas nunca cambian.",
  1979: "Nace VisiCalc, la primera hoja de cálculo. Excel tiene un abuelo.",
  1980: "Pac-Man devora monedas en todo el mundo.",
  1981: "Sale la IBM PC con MS-DOS. La pantalla negra empieza su reinado.",
  1982: "El Commodore 64 se convierte en la computadora más vendida de la historia.",
  1983: "Nace C++ y Turbo Pascal. También la palabra internet.",
  1984: "Apple presenta el Macintosh. Steve Jobs lo saca de una bolsa.",
  1985: "Sale Windows 1.0 y Super Mario Bros. Uno de los dos envejeció mejor.",
  1986: "Se lanza el disquete de 3.5 pulgadas. El ícono de guardar nace aquí.",
  1987: "Nace Perl y Photoshop está en camino.",
  1988: "El gusano Morris tumba buena parte de internet. Primer gran susto.",
  1989: "Tim Berners-Lee propone la World Wide Web en un memo.",
  1990: "Se publica la primera página web. Tenía solo texto y enlaces.",
  1991: "Linus Torvalds sube Linux y Guido van Rossum publica Python.",
  1992: "Windows 3.1 y el buscaminas roban horas de oficina.",
  1993: "Sale Mosaic, el navegador que hizo la web visual. También Doom.",
  1994: "Nace Netscape y Yahoo. La web empieza a tener directorio.",
  1995: "El año dorado: Java, JavaScript, PHP, Ruby, Windows 95 y Amazon.",
  1996: "Nace Hotmail y el Tamagotchi. Dos cosas que había que alimentar.",
  1997: "Se lanza Netflix por correo y Deep Blue vence a Kasparov.",
  1998: "Nace Google en un garaje. El sonido del módem era la banda sonora.",
  1999: "Napster cambia la música y todos temen al Y2K.",
  2000: "El Y2K no pasó nada. Sale el Nokia 3310 y la burbuja punto com explota.",
  2001: "Wikipedia, el iPod, Windows XP y Mac OS X. Un año cargado.",
  2002: "Nace Mozilla Firefox como Phoenix. Los pop-ups empiezan a perder.",
  2003: "MySpace y WordPress. Medio internet aprende HTML para decorar su perfil.",
  2004: "Facebook nace en un dormitorio. Gmail regala 1 GB y parece infinito.",
  2005: "YouTube sube su primer video en el zoológico. Nace Git y Reddit.",
  2006: "Twitter tiene 140 caracteres. Amazon lanza AWS y jQuery simplifica todo.",
  2007: "Steve Jobs presenta el iPhone. El teclado físico empieza a despedirse.",
  2008: "Nace GitHub, Android, Chrome y Stack Overflow. Tu carrera te lo agradece.",
  2009: "Sale Node.js y Go. Minecraft empieza en alfa. Bitcoin mina su primer bloque.",
  2010: "El iPad, Instagram y AngularJS. Las apps móviles lo son todo.",
  2011: "Kotlin, Dart y Bootstrap. Adobe abandona Flash en móviles.",
  2012: "Sale la Raspberry Pi por 35 dólares y TypeScript llega a JavaScript.",
  2013: "Nace React y Docker. Slack empieza a reemplazar el correo interno.",
  2014: "Swift reemplaza a Objective-C. Vue.js aparece en GitHub.",
  2015: "Rust 1.0, Visual Studio Code, GraphQL y ES6. JavaScript se vuelve serio.",
  2016: "Pokémon Go llena las calles. Sale Angular 2 y llega Yarn.",
  2017: "Flutter llega en alfa, Kotlin es oficial para Android y nace el Transformer.",
  2018: "GitHub pasa a Microsoft. Deno y los React Hooks se anuncian.",
  2019: "Sale VS Code Remote y Deno 0.1. TikTok explota en todo el mundo.",
  2020: "Todo el mundo aprende Zoom. Deno 1.0, Apple Silicon y el home office eterno.",
  2021: "GitHub Copilot escribe su primera línea. Sale Windows 11.",
  2022: "ChatGPT sale en noviembre y cambia la conversación. Bun 0.1 aparece.",
  2023: "Explota la IA generativa. Todo proyecto nuevo tiene un prompt.",
  2024: "Los agentes de código empiezan a programar contigo. Sale React 19.",
  2025: "Programar es conversar. Los modelos escriben, tú decides.",
  2026: "Estás aquí. Tu primer proyecto es este año. Bienvenido.",
};

export function factFor(year: number): string {
  if (YEAR_FACTS[year]) return YEAR_FACTS[year];
  const years = Object.keys(YEAR_FACTS).map(Number);
  const nearest = years.reduce((a, b) => (Math.abs(b - year) < Math.abs(a - year) ? b : a));
  return YEAR_FACTS[nearest];
}
